# Generated by Django 3.2.13 on 2023-07-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
